/**
 * @brief Configuration file for bootloader
 */

#ifndef BOOTLOADER_CONFIG_H_
#define BOOTLOADER_CONFIG_H_

#include <stdint.h>
#include <stdbool.h>
#include BOARD_HEADER


#define BTL_DRIVER_UART_RX_BUFFER_SIZE 512
#define BTL_DRIVER_UART_TX_BUFFER_SIZE 128

#define BSP_SERIAL_APP_PORT BTL_SERIAL_APP_PORT
#define HAL_SERIAL_APP_BAUD_RATE BTL_SERIAL_APP_BAUD_RATE
#define BSP_SERIAL_APP_TX_PORT BTL_SERIAL_APP_TX_PORT
#define BSP_SERIAL_APP_TX_PIN BTL_SERIAL_APP_TX_PIN
#define BSP_SERIAL_APP_RX_PORT BTL_SERIAL_APP_RX_PORT
#define BSP_SERIAL_APP_RX_PIN BTL_SERIAL_APP_RX_PIN
#define BSP_SERIAL_APP_TX_LOC BTL_SERIAL_APP_TX_LOC
#define BSP_SERIAL_APP_RX_LOC BTL_SERIAL_APP_RX_LOC

#ifdef __cplusplus
extern "C" {
#endif



#ifdef __cplusplus
}
#endif


#endif /* BOOTLOADER_CONFIG_H_ */
